"""visible_archive

Revision ID: 2d0eea9d0aaa
Revises: 3504af55fe85
Create Date: 2022-04-04 19:39:32.692338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0eea9d0aaa'
down_revision = '3504af55fe85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('point', sa.Column('visible', sa.Boolean(), nullable=True))

    op.execute("UPDATE point SET archived = false")
    op.execute("UPDATE point SET visible = true")

    op.alter_column('point', 'archived', nullable=False)
    op.alter_column('point', 'visible', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'visible')
    op.drop_column('point', 'archived')
    # ### end Alembic commands ###
