"""empty message

Revision ID: 3c990b8a15c2
Revises: 
Create Date: 2021-05-22 11:56:43.038642

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = '3c990b8a15c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_reported', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('disability', sa.String(length=5), nullable=True),
    sa.Column('disability_type', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('mobility_aid', sa.String(length=5), nullable=True),
    sa.Column('mobility_aid_type', sa.String(length=50), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrier_detail', sa.String(length=50), nullable=True),
    sa.Column('barrier_subtype', sa.String(length=25), nullable=True),
    sa.Column('barrier_type', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concern_type', sa.String(length=20), nullable=True),
    sa.Column('concern_with', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.String(length=10), nullable=True),
    sa.Column('incident_with', sa.String(length=25), nullable=True),
    sa.Column('injury_type', sa.String(length=20), nullable=True),
    sa.Column('involvement', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_table('incident')
    op.drop_table('concern')
    op.drop_table('barrier')
    op.drop_table('amenity')
    op.drop_table('point')
    # ### end Alembic commands ###
