"""Add heard from field

Revision ID: 4e556efcb41d
Revises: 2d0eea9d0aaa
Create Date: 2022-12-05 19:23:34.147275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e556efcb41d'
down_revision = '2d0eea9d0aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('heard_about', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'heard_about')
    # ### end Alembic commands ###
