"""empty message

Revision ID: ccbada1de72d
Revises: 974ac9b8bb63
Create Date: 2022-02-07 20:06:45.127699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbada1de72d'
down_revision = '974ac9b8bb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident', 'involvement',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('point', 'disability',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('point', 'mobility_aid',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point', 'mobility_aid',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('point', 'disability',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('incident', 'involvement',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
